version: '3'

services:
  pg:
    build:
      context: pg
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always

  rabbit:
    image: "rabbitmq"
    ports:
     - "5672:5672"

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
          - "rabbit"

#  consumer:
#      build:
#        context: ./consumer
#        dockerfile: Dockerfile
#      depends_on:
#            - "rabbit"